name: Release

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: yarn build
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: yarn build
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
