name: Public Npm

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          yarn install
          yarn build # 这是我的项目的打包命令，你也可以改成你的

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: 'master'
